SELinuxProject/setools

setools/policyrep/terule.pxi
Added missing ** to pass kwargs as kwargs instead of as a dictionary.
Signed-off-by: Riechers, Daniel J <daniel.riechers@rockwellcollins.com>
=> terule: Fixed evaluate kwargs

setools/diff/terules.py, setools/policyrep/terule.pxi, tests/diff.py, tests/diff_left.conf, tests/diff_left_redundant.conf, tests/diff_left_standard.conf, tests/diff_right_rmisid.conf
The primary motivation for the change is to correctly handle redundant
rules. Recent changes in the SELinux toolchain added support for an
optimization that removes redundant rules from a policy. These are
conditional rules that are either already specified in unconditional
policy or rules using types that are also specified more generally
through an attribute. Since attributes are always expanded in sediff,
the second type of redundant rules are already effectively removed. But
redundant conditional rules show up as differences when a binary version
of a policy that has been optimized is compared to one that has not been.
A secondary motivation for the change is to reduce memory usage and diff
times. A modern Fedora policy cannot be diffed with a system with less than
32Gb of memory and …
=> Change how differences in AV rules are generated in sediff

setools/perm_map
sendto on some object classes was marked as a read when it should be
a write.
=> Correct permmap stating that sendto is a read.

seinfo, sesearch, setools/policyrep/selinux.pxd, setools/policyrep/util.pxi
Translate old boolean names based on /etc/selinux/*/booleans.subs_dist
file.
=> Support old boolean names in policy query

.github/workflows/tests.yml, README.md, setools/policyrep/sepol.pxd, setools/policyrep/terule.pxi, tests/policyrep/selinuxpolicy.conf
We are considering to merge SELinux userspace patches [1] that would cause setools to fail to build & link against libsepol. @jwcart2 already started working on abstracting a proper public API for use by setools instead of relying on libsepol's internals, but it may not be ready soon enough. This PR aims to prepare the patches that will be needed to make setools work with the new libsepol.
The first patch is intended only for testing - it directs the Travis CI to fetch userspace from a branch that contains the pending libsepol patches; the second patch does the actual conversion; and the last patch adds a few more filename transition rules to one of the test policies to exercise some corner cases in the new representation.
This PR is just an initial draft - feel free to suggest changes or …
=> RFC: Adapt setools to the new libsepol's filename transition representation

setoolsgui/apol/boolquery.py, setoolsgui/apol/boundsquery.py, setoolsgui/apol/categoryquery.py, setoolsgui/apol/commonquery.py, setoolsgui/apol/constraintquery.py, setoolsgui/apol/defaultquery.py, setoolsgui/apol/dta.py, setoolsgui/apol/fsusequery.py, setoolsgui/apol/genfsconquery.py, setoolsgui/apol/ibendportconquery.py, setoolsgui/apol/ibpkeyconquery.py, setoolsgui/apol/infoflow.py, setoolsgui/apol/initsidquery.py, setoolsgui/apol/mlsrulequery.py, setoolsgui/apol/netifconquery.py, setoolsgui/apol/nodeconquery.py, setoolsgui/apol/objclassquery.py, setoolsgui/apol/portconquery.py, setoolsgui/apol/rbacrulequery.py, setoolsgui/apol/rolequery.py, setoolsgui/apol/sensitivityquery.py, setoolsgui/apol/terulequery.py, setoolsgui/apol/typeattrquery.py, setoolsgui/apol/typequery.py, setoolsgui/apol/userquery.py
Suppress errors like this:
Exception ignored in: <function DomainTransitionAnalysisTab.__del__ at 0x7fcb4e93c1f0>
Traceback (most recent call last):
File "/home/pebenito/projects/setools/setoolsgui/apol/dta.py", line 54, in __del__
self.thread.quit()
RuntimeError: wrapped C/C++ object of type ResultsUpdater has been deleted
Exception ignored in: <function ResultsUpdater.__del__ at 0x7fcb4e943550>
Traceback (most recent call last):
File "/home/pebenito/projects/setools/setoolsgui/apol/dta.py", line 449, in __del__
self.wait()
RuntimeError: wrapped C/C++ object of type ResultsUpdater has been deleted
Exception ignored in: <function BrowserUpdater.__del__ at 0x7fcb4e943820>
Traceback (most recent call last):
File "/home/pebenito/projects/setools/setoolsgui/apol/dta.py", line 538, in __del__ …
=> apol: Suppress RuntimeErrors in analysis tab destructors.

ChangeLog, setools/checker/descriptors.py, tests/checker/checker-valid.ini
The parsing did not correctly handle newline and tab characters.
Add a multiline value in the sechecker test config file to make sure this
case is tested.
=> ConfigSetDescriptor: Fix parsing of multiline values.

setools/perm_map
Add watch permissions, added in https://github.com/SELinuxProject/selinux-kernel/commit/ac5656d8a4cdd93cd2c74355ed12e5617817e0e7
Add `perf_event` class, added in https://github.com/SELinuxProject/selinux-kernel/commit/da97e18458fb42d7c00fac5fd1c56a3896ec666e
Add `lockdown` class, added in https://github.com/SELinuxProject/selinux-kernel/commit/59438b46471ae6cdfb761afc8c9beaf1e428a331
Add `anon_inode` class, added in https://github.com/SELinuxProject/selinux-kernel/commit/29cd6591ab6fee3125ea5c1bf350f5013bc615e1
Weight removed permission with value 10, see https://github.com/SELinuxProject/selinux-kernel/commit/42a9699a9fa179c0054ea3cf5ad3cc67104a6162
Drop inexistent `permissions execute_no_trans` and `entrypoint` from `chr_file`
Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
=> Update permission map

setools/policyrep/constraint.pxi, setools/policyrep/objclass.pxi, setools/policyrep/role.pxi, setools/policyrep/user.pxi
There are few places where frozenset is used. Given that frozenset is an unordered
collection the output generated from this is unpredictable.
The following command outputs are fixed using sorted() on frozensets:
seinfo --constrain
seinfo --common
seinfo -c -x
seinfo -r -x
seinfo -u -x
Fixes: https://github.com/SELinuxProject/setools/issues/65
Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
=> Make seinfo output predictable

sedta, seinfoflow
* Make a brief output for sedta and seinfoflow. This is the default. Use `--full` to get the full ouptput.
* Make the `-m` option of seinfoflow optional.
=> Minor improvements to sedta and seinfoflow

setools/dta.py, setools/infoflow.py
The CLI tools get installed to most distros, but sedta and seinfoflow are not typically used or separated into a different package. This will allow seinfo, sesearch, and sediff to function if NetworkX is missing, since they don't require it.
=> Make NetworkX optional.

man/sesearch.1
The old text does not match the behavior observed in practice or the
description in the --help flag
=> Update text of man page for -ep flag

man/sesearch.1, sesearch
The perms_subset rule search flag matches rules where the searched perms
are a subset of the rule perms.  This flag is currently only exposed via
apol, and this commit exposes it via sesearch
Signed-off-by: Daniel Burgener <dburgener@linux.microsoft.com>
=> Add -Sp argument to sesearch to serve as front end for perms_subset

pyproject.toml
Attempting to install the `setools` package using `pip install .` causes errors if `Cython` is not already installed. This is due to the import/use of `Cython.Build.cythonize` within the `setup.py` file. By adding a `pyproject.toml` file, this can be fixed by causing a temporary `Cython` installation to be used for the setup of `setools`
=> Add pyproject.toml to fix Cython dependency issue

setoolsgui/tableview.py, setoolsgui/treeview.py
The Ctrl-C and Ctrl-X shortcuts are handled by the copy() and cut() functions in the ApolMainWindow, which just get the currently focused widget and call its function of the same name.
However, the custom SEToolsTableView and SEToolsTreeView widgets do not use these functions to implement Ctrl-C/X, but instead override the event() function and check if each received event is a copy/cut key sequence. Functionally this is the same as copy() and cut(), but this leads to an abort in newer versions for Fedora and/or PyQT5 (the reason is not obvious).
To avoid the abort, and arguably make things a little more clear, this overrides the copy() and cut() functions in these widgets, moves the specialize copy logic into them, and removes the event() function.
Closes #77
=> Override copy() and cut() functions for custom tree/table widgets

.github/workflows/tests.yml, setools/dta.py, setools/infoflow.py
Python 3.6 is not available on Ubuntu 22.04.
=> tests.yml: Pin ubuntu-20.04 to keep appropriate Python versions.

setools/checker/descriptors.py, setools/descriptors.py, setools/diff/descriptors.py, setools/diff/typing.py, setools/dta.py, setools/infoflow.py, setools/permmap.py
* Store data in the associated object instead of the descriptor itself, making the weak reference use unnecessary.
* Use `__set_name__()`.
=> Refine descriptors

sediff, setools/diff/bool.py, setools/diff/bounds.py, setools/diff/commons.py, setools/diff/default.py, setools/diff/difference.py, setools/diff/fsuse.py, setools/diff/genfscon.py, setools/diff/ibendportcon.py, setools/diff/ibpkeycon.py, setools/diff/initsid.py, setools/diff/mls.py, setools/diff/mlsrules.py, setools/diff/netifcon.py, setools/diff/nodecon.py, setools/diff/objclass.py, setools/diff/portcon.py, setools/diff/properties.py, setools/diff/rbacrules.py, setools/diff/roles.py, setools/diff/terules.py, setools/diff/typeattr.py, setools/diff/types.py, setools/diff/typing.py, setools/diff/users.py, setools/infoflow.py, setools/mixins.py, setools/permmap.py, tests/test_diff.py, tests/test_permmap.py
Add backwards compatibility for tuple usage.
=> diff/permmap: Replace named tuples with dataclasses.

man/seinfoflow.1, seinfoflow
Also remove references to the sepolgen permission map from the seinfoflow man page.
=> seinfoflow: Add -r option to get flows into the source type.

setools/policyrep/terule.pxi
=> AVRule/AVRuleXperm: Treat rules with no permissions as invalid policy.

setools/policyrep/selinuxpolicy.pxi, setools/policyrep/sepol.pxd
Cython 3.0 is more strict.  The change fixes this issue:
```
setools/policyrep/selinuxpolicy.pxi:685:46: Cannot assign type 'void (void *, sepol_handle_t *, const char *, ...) except *' to 'msg_callback'
```
Additionally, the msg_callback is not typedef-ed in `sepol/debug.h`, so it must be explicitly defined in `sepol.pxd` for the casting to work.
=> SELinuxPolicy: Add explicit cast for libspol message callback.

man/sesearch.1, sesearch
Using -p, -x, and -b with RBAC or MLS searches is an error as these expressions never yield results.
Fixes #111
Fully specify --type/role/range_transition options. Python's argparse argument abbreviation feature provides backwards compatibility.
=> sesearch: Raise parse error mixing expressions unused by RBAC/MLS searches.

setools/policyrep/util.pxi
Compiling locally can cause:
```
Compiling setools/policyrep.pyx because it changed.
[1/1] Cythonizing setools/policyrep.pyx
Error compiling Cython file:
------------------------------------------------------------
...
self.sh = sepol.sepol_handle_create()
if self.sh == NULL:
raise MemoryError
sepol.sepol_msg_set_callback(self.sh, sepol_logging_callback, self.handle)
^
------------------------------------------------------------
setools/policyrep/selinuxpolicy.pxi:671:46: Cannot assign type 'void (void *, sepol_handle_t *, const char *, ...) except *' to 'msg_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, sepol_handle_t *, const char *, ...) except *'.
Traceback (most recent call last):
File "setools/setup.py", line 162, in <module> …
```
=> policyrep: Callback for C code should be noexcept

setools/policyrep/constraint.pxi, tests/library/constraintquery.conf, tests/library/test_constraintquery.py
The existing algorithm to convert constraints from postfix to infix notation does not insert parentheses correctly. This change addresses the problem.
For example, given the following expression in the source policy:
( t2 == ssh_client_packet_t or t2 == ssh_server_packet_t ) and t1 == sshd_t
The output currently returned would be:
t2 == ssh_client_packet_t or ( t2 == ssh_server_packet_t ) and ( t1 == sshd_t )
Which of course is not equivalent to the actual expression due to the lack of parentheses surrounding the "or" expression.
=> Correct inclusion of parentheses when outputing constraints

tests/gui/conftest.py
tests/gui/conftest.py:20
setools/tests/gui/conftest.py:20: PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)
see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
def pytest_ignore_collect(collection_path: pathlib.Path, path,
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=> tests: drop deprecated parameter

setools/policyrep/selinuxpolicy.pxi
Support gaps in the type array which are supported by libsepol.
Encountered while experimenting on a policy optimization step that removes unused type-attributes.
=> Support gaps in type array

setools/policyrep/typeattr.pxi, tests/conftest.py
- Fix new mypy issues in tests/conftest.py
- Stabilize alias and attribute output in Type.statement().
=> Fix ci tests

pyproject.toml
The dependency was dropped in 99a1cf3b50cd8bf502b5070293c4d1bf792d1566
=> Remove redundant runtime requirement on setuptools

.github/workflows/tests.yml, seinfo, setools/devicetreeconquery.py, setools/exception.py, setools/fsusequery.py, setools/genfsconquery.py, setools/ibendportconquery.py, setools/ibpkeyconquery.py, setools/initsidquery.py, setools/iomemconquery.py, setools/ioportconquery.py, setools/netifconquery.py, setools/nodeconquery.py, setools/pcideviceconquery.py, setools/pirqconquery.py, setools/policyrep/netcontext.pxi, setools/policyrep/selinuxpolicy.pxi, setools/policyrep/xencontext.pxi, setools/portconquery.py, setools/query.py, tests/conftest.py
* SELinux and Xen query arguments are now defined in separate argument groups (`selinux` and `xen`), and the tool enforces that arguments from both groups cannot be combined in a single invocation. This ensures users do not mix incompatible queries. (`seinfo`, [seinfoL91-R121](diffhunk://#diff-a1dc70ae19a33ab848e21d7206a46138d32ebd84c6812c99d125057a616a8528L91-R121))
* At runtime, the tool checks the loaded policy's platform (SELinux or Xen) and raises errors if queries from the wrong group are specified, preventing platform mismatches. (`seinfo`, [seinfoR146-R153](diffhunk://#diff-a1dc70ae19a33ab848e21d7206a46138d32ebd84c6812c99d125057a616a8528R146-R153))
* Each query class now declares a `required_platform` attribute, specifying whether it is valid for SELinux or Xen policies. This …
=> Seinfo improvements
